{melodic} ros-distro.inc: add mapping for libusb-dev
* fixes:
ERROR: Nothing PROVIDES 'UNRESOLVED-libusb-dev' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/phidgets-drivers/libphidget21_0.7.9-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/joystick-drivers/ps3joy_1.13.0-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/cob-extern/libphidgets_0.6.14-1.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/kobuki-core/kobuki-ftdi_0.7.8.bb, /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/schunk-modular-robotics/schunk-sdh_0.6.14-1.bb DEPENDS on or otherwise requires it)
NOTE: Runtime target 'libphidget21' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidget21', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'ps3joy' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ps3joy', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'freight-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freight-bringup', 'ps3joy', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'pr2-apps' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-apps', 'pr2-teleop-general', 'ps3joy', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'pr2-teleop-general' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['pr2-teleop-general', 'ps3joy', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'libphidgets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libphidgets', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'cob-phidgets' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-phidgets', 'libphidgets', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'cob-voltage-control' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-voltage-control', 'cob-phidgets', 'libphidgets', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'cob-phidget-power-state' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-phidget-power-state', 'cob-phidgets', 'libphidgets', 'UNRESOLVED-libusb-dev']
NOTE: Runtime target 'cob-phidget-em-state' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cob-phidget-em-state', 'cob-phidgets', 'libphidgets', 'UNRESOLVED-libusb-dev']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>