{melodic} multisense-ros: work around typo in rosdep/base.yaml
* fixes:
ERROR: Nothing PROVIDES 'libjpeq-turbo' (but /jenkins/mjansa/build-ros/ros1-melodic-thud/meta-ros/meta-ros1-melodic/generated-recipes/multisense-ros/multisense-ros_4.0.2.bb DEPENDS on or otherwise requires it). Close matches:
  libjpeg-turbo
  libjpeg-turbo-native
NOTE: Runtime target 'multisense-ros' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'packagegroup-ros-world-melodic' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world-melodic', 'multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'ros-image-world' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['ros-image-world', 'packagegroup-ros-world', 'packagegroup-ros-world-melodic', 'multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'multisense' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense', 'multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'multisense-cal-check' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-cal-check', 'multisense-ros', 'libjpeq-turbo']
NOTE: Runtime target 'multisense-bringup' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['multisense-bringup', 'multisense-ros', 'libjpeq-turbo']

Signed-off-by: Martin Jansa <martin.jansa@lge.com>