fastrtps: fix tinyxml2 library search
* fixes rmw-fastrtps-cpp failure:
  http://errors.yoctoproject.org/Errors/Details/174717/

  DEBUG: Executing shell function do_compile
  NOTE: VERBOSE=1 cmake --build TOPDIR/tmp-glibc/work/aarch64-oe-linux/rmw-fastrtps-cpp/git-r0/build --target all -- -j 9
  ninja: error: 'TOPDIR/tmp-glibc/work/aarch64-oe-linux/fastrtps/git-r0/recipe-sysroot/usr/lib/libtinyxml2.so', needed by 'librmw_fastrtps_cpp.so', missing and no known rule to make it
  WARNING: TOPDIR/tmp-glibc/work/aarch64-oe-linux/rmw-fastrtps-cpp/git-r0/temp/run.do_compile.13110:1 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build 'TOPDIR/tmp-glibc/work/aarch64-oe-linux/rmw-fastrtps-cpp/git-r0/build' "$@" -- -j 9'
  ERROR: Function failed: do_compile (log file is located at TOPDIR/tmp-glibc/work/aarch64-oe-linux/rmw-fastrtps-cpp/git-r0/temp/log.do_compile.13110)

* it was caused by fastrtps's /usr/lib/fastrtps/cmake/fastrtpsTargets.cmake
  containing the full path to libtinyxml2.so inside fastrtps's WORKDIR
  which might be already removed by rm_work by the time when
  rmw-fastrtps-cpp is being built

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>