{melodic} cartographer: drop one test to fix build with gcc-9
* see https://github.com/googlecartographer/cartographer/issues/1653
* fixes:
cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/bits/stl_map.h: In instantiation of 'std::map<_Key, _Tp, _Compare, _Alloc>::map(_InputIterator, _InputIterator) [with _InputIterator = cartographer::mapping::DynamicGrid<cartographer::mapping::NestedGrid<cartographer::mapping::FlatGrid<short unsigned int, 3>, 3> >::Iterator; _Key = Eigen::Matrix<int, 3, 1>; _Tp = float; _Compare = cartographer::mapping::{anonymous}::EigenComparator; _Alloc = std::allocator<std::pair<const Eigen::Matrix<int, 3, 1>, float> >]':
cartographer/1.0.0-1-r0/git/cartographer/mapping/3d/hybrid_grid_test.cc:216:47:   required from here
cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/bits/stl_map.h:273:4: error: no matching function for call to 'std::_Rb_tree<Eigen::Matrix<int, 3, 1>, std::pair<const Eigen::Matrix<int, 3, 1>, float>, std::_Select1st<std::pair<const Eigen::Matrix<int, 3, 1>, float> >, cartographer::mapping::{anonymous}::EigenComparator, std::allocator<std::pair<const Eigen::Matrix<int, 3, 1>, float> > >::_M_insert_range_unique(cartographer::mapping::DynamicGrid<cartographer::mapping::NestedGrid<cartographer::mapping::FlatGrid<short unsigned int, 3>, 3> >::Iterator&, cartographer::mapping::DynamicGrid<cartographer::mapping::NestedGrid<cartographer::mapping::FlatGrid<short unsigned int, 3>, 3> >::Iterator&)'
  273 |  { _M_t._M_insert_range_unique(__first, __last); }
      |    ^~~~
In file included from cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/map:60,
                 from cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/ceres/ordered_groups.h:34,
                 from cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/ceres/ceres.h:52,
                 from cartographer/1.0.0-1-r0/git/cartographer/common/math.h:25,
                 from cartographer/1.0.0-1-r0/git/cartographer/mapping/3d/hybrid_grid.h:28,
                 from cartographer/1.0.0-1-r0/git/cartographer/mapping/3d/hybrid_grid_test.cc:17:
cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/bits/stl_tree.h:1109:2: note: candidate: 'template<class _InputIterator> std::__enable_if_t<std::is_same<_Val, typename std::iterator_traits<_InputIterator>::value_type>::value> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_range_unique(_InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _Key = Eigen::Matrix<int, 3, 1>; _Val = std::pair<const Eigen::Matrix<int, 3, 1>, float>; _KeyOfValue = std::_Select1st<std::pair<const Eigen::Matrix<int, 3, 1>, float> >; _Compare = cartographer::mapping::{anonymous}::EigenComparator; _Alloc = std::allocator<std::pair<const Eigen::Matrix<int, 3, 1>, float> >]'
 1109 |  _M_insert_range_unique(_InputIterator __first, _InputIterator __last)
      |  ^~~~~~~~~~~~~~~~~~~~~~
cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/bits/stl_tree.h:1109:2: note:   template argument deduction/substitution failed:
cartographer/1.0.0-1-r0/recipe-sysroot/usr/include/c++/9.2.0/bits/stl_tree.h: In substitution of 'template<class _InputIterator> std::__enable_if_t<std::is_same<std::pair<const Eigen::Matrix<int, 3, 1>, float>, typename std::iterator_traits<_Iterator>::value_type>::value, void> std::_Rb_tree<Eigen::Matrix<int, 3, 1>, std::pair<const Eigen::Matrix<int, 3, 1>, float>, std::_Select1st<std::pair<const Eigen::Matrix<int, 3, 1>, float> >, cartographer::mapping::{anonymous}::EigenComparator, std::allocator<std::pair<const Eigen::Matrix<int, 3, 1>, float> > >::_M_insert_range_unique<_InputIterator>(_InputIterator, _InputIterator) [with _InputIterator = cartographer::mapping::DynamicGrid<cartographer::mapping::NestedGrid<cartographer::mapping::FlatGrid<short unsigned int, 3>, 3> >::Iterator]':

Signed-off-by: Martin Jansa <martin.jansa@lge.com>